export const TRANSACTION = [
    {
      id: 0,
      accountId: 0,
      transType: "income",
      amount: 100000,
      date: "2021-08-16",
    },
    {
      id: 1,
      accountId: 0,
      transType: "expense",
      date: "2021-08-19",
      voucher: "واؤچر", 
      bank : "سقایہ ویلفئیر سوسائٹی", 
      reciever : "محمد امین خان", 
      detail : "-", 
      voucherNo : "-",
      amount: 50000,
    },
    {
      id: 2,
      accountId: 0,
      transType: "income",
      amount: 50000,
      date: "2021-08-10",
    },
    {
      id: 3,
      accountId: 0,
      transType: "expense",
      date: "2021-08-13",
      voucher: "واؤچر", 
      bank : "سقایہ ویلفئیر سوسائٹی", 
      reciever : "محمد امین خان", 
      detail : "-", 
      voucherNo : "-",
      amount: 40000,
    },
    ////////////////////////////////////////////////////
    {
      id: 4,
      accountId: 1,
      transType: "income",
      date: "2021-08-16",
      amount: 10000,
    },
    {
      id: 5,
      accountId: 1,
      transType: "income",
      amount: 15000,
      date: "2021-08-19",
    },
    {
      id: 6,
      accountId: 1,
      transType: "expense",
      date: "2021-08-19",
      voucher: "واؤچر", 
      bank : "سقایہ ویلفئیر سوسائٹی", 
      reciever : "محمد امین خان", 
      detail : "-", 
      voucherNo : "-",
      amount: 14000,
    },
    //////////////////////////////
    {
      id: 7,
      accountId: 2,
      transType: "income",
      date: "2021-08-1",
      amount: 800000,
    },
    {
      id: 8,
      accountId: 2,
      transType: "expense",
      date: "2021-08-8",
      voucher: "واؤچر", 
      bank : "سقایہ ویلفئیر سوسائٹی", 
      reciever : "محمد امین خان", 
      detail : "-", 
      voucherNo : "-",
      amount: 400000,
    },
    {
      id: 9,
      accountId: 2,
      transType: "income",
      date: "2021-08-3",
      amount: 200000,
    },
    {
      id: 10,
      accountId: 2,
      transType: "expense",
      date: "2021-08-9",
      voucher: "واؤچر", 
      bank : "سقایہ ویلفئیر سوسائٹی", 
      reciever : "محمد امین خان", 
      detail : "-", 
      voucherNo : "-",
      amount: 200000,
    },
    ///////////////////////////////
    {
      id: 11,
      accountId: 3,
      transType: "income",
      date: "2021-05-2",
      amount: 100000,
    },
    {
      id: 12,
      accountId: 3,
      transType: "expense",
      date: "2021-08-19",
      voucher: "واؤچر", 
      bank : "سقایہ ویلفئیر سوسائٹی", 
      reciever : "محمد امین خان", 
      detail : "-", 
      voucherNo : "-",
      amount: 50000,
    },
    {
      id: 13,
      accountId: 3,
      transType: "income",
      amount: 50000,
      date: "2021-06-19",
    },
    {
      id: 14,
      accountId: 3,
      transType: "expense",
      date: "2021-08-22",
      voucher: "واؤچر", 
      bank : "سقایہ ویلفئیر سوسائٹی", 
      reciever : "محمد امین خان", 
      detail : "-", 
      voucherNo : "-",
      amount: 40000,
    },
    {
      id: 15,
      accountId: 1,
      transType: "expense",
      date: "2021-08-16",
      voucher: "واؤچر", 
      bank : "سقایہ ویلفئیر سوسائٹی", 
      reciever : "محمد امین خان", 
      detail : "-", 
      voucherNo : "-",
      amount: 5000,
    }
  ];
