export const TRANSACTION = [
  {
    id: 0,
    accountId: 0,
    masjidId: 0,
    transType: "income",
    date: "2021-08-14",
    voucher: "", 
    bank : "", 
    reciever : "", 
    detail : "", 
    voucherNo : "",
    amount: 100000,
  },
  {
    id: 1,
    accountId: 0,
    masjidId: 0,
    transType: "income",
    date: "2021-08-15",
    voucher: "", 
    bank : "", 
    reciever : "", 
    detail : "", 
    voucherNo : "",
    amount: 50000,
  },
  {
    id: 2,
    accountId: 0,
    masjidId: 0,
    transType: "expense",
    date: "2021-08-19",
    voucher: "واؤچر", 
    bank : "سقایہ ویلفئیر سوسائٹی", 
    reciever : "محمد امین خان", 
    detail : "-", 
    voucherNo : "-",
    amount: 10000,
  },
  {
    id: 3,
    accountId: 0,
    masjidId: 1,
    transType: "expense",
    date: "2021-08-20",
    voucher: "واؤچر", 
    bank : "سقایہ ویلفئیر سوسائٹی", 
    reciever : "محمد امین خان", 
    detail : "-", 
    voucherNo : "-",
    amount: 20000,
  },
  {
    id: 4,
    accountId: 0,
    masjidId: 0,
    transType: "expense",
    date: "2021-08-19",
    voucher: "واؤچر", 
    bank : "سقایہ ویلفئیر سوسائٹی", 
    reciever : "محمد امین خان", 
    detail : "-", 
    voucherNo : "-",
    amount: 10000,
  },
  {
    id: 5,
    accountId: 0,
    masjidId: 1,
    transType: "expense",
    date: "2021-08-20",
    voucher: "واؤچر", 
    bank : "سقایہ ویلفئیر سوسائٹی", 
    reciever : "محمد امین خان", 
    detail : "-", 
    voucherNo : "-",
    amount: 20000,
  },
  {
    id: 6,
    accountId: 0,
    masjidId: 2,
    transType: "expense",
    date: "2021-08-19",
    voucher: "واؤچر", 
    bank : "سقایہ ویلفئیر سوسائٹی", 
    reciever : "محمد امین خان", 
    detail : "-", 
    voucherNo : "-",
    amount: 10000,
  },
  {
    id: 7,
    accountId: 0,
    masjidId: 3,
    transType: "expense",
    date: "2021-08-20",
    voucher: "واؤچر", 
    bank : "سقایہ ویلفئیر سوسائٹی", 
    reciever : "محمد امین خان", 
    detail : "-", 
    voucherNo : "-",
    amount: 20000,
  },
   ////////////////////////////////////////////////////
  {
    id: 8,
    accountId: 1,
    masjidId: 1,
    transType: "income",
    date: "2021-08-10",
    voucher: "", 
    bank : "", 
    reciever : "", 
    detail : "", 
    voucherNo : "",
    amount: 50000,
  },
  {
    id: 9,
    accountId: 1,
    masjidId: 1,
    transType: "income",
    date: "2021-08-16",
    voucher: "", 
    bank : "", 
    reciever : "", 
    detail : "", 
    voucherNo : "",
    amount: 10000,
  },
  {
    id: 10,
    accountId: 1,
    masjidId: 1,
    transType: "expense",
    date: "2021-08-13",
    voucher: "واؤچر", 
    bank : "سقایہ ویلفئیر سوسائٹی", 
    reciever : "محمد امین خان", 
    detail : "-", 
    voucherNo : "-",
    amount: 10000,
  },
  {
    id: 11,
    accountId: 1,
    masjidId: 1,
    transType: "expense",
    date: "2021-08-14",
    voucher: "واؤچر", 
    bank : "سقایہ ویلفئیر سوسائٹی", 
    reciever : "محمد امین خان", 
    detail : "-", 
    voucherNo : "-",
    amount: 20000,
  },
   ////////////////////////////////////////////////////
  {
    id: 12,
    accountId: 2,
    masjidId: 2,
    transType: "income",
    date: "2021-08-1",
    voucher: "", 
    bank : "", 
    reciever : "", 
    detail : "", 
    voucherNo : "",
    amount: 30000,
  },
  {
    id: 13,
    accountId: 2,
    masjidId: 2,
    transType: "income",
    date: "2021-08-1",
    voucher: "", 
    bank : "", 
    reciever : "", 
    detail : "", 
    voucherNo : "",
    amount: 40000,
  },
  {
    id: 14,
    accountId: 2,
    masjidId: 2,
    transType: "expense",
    date: "2021-08-13",
    voucher: "واؤچر", 
    bank : "سقایہ ویلفئیر سوسائٹی", 
    reciever : "محمد امین خان", 
    detail : "-", 
    voucherNo : "-",
    amount: 50000,
  },
  {
    id: 15,
    accountId: 2,
    masjidId: 3,
    transType: "expense",
    date: "2021-08-13",
    voucher: "واؤچر", 
    bank : "سقایہ ویلفئیر سوسائٹی", 
    reciever : "محمد امین خان", 
    detail : "-", 
    voucherNo : "-",
    amount: 10000,
  },
   ////////////////////////////////////////////////////
  {
    id: 16,
    accountId: 3,
    masjidId: 3,
    transType: "income",
    date: "2021-08-3",
    voucher: "", 
    bank : "", 
    reciever : "", 
    detail : "", 
    voucherNo : "",
    amount: 200000,
  },
  {
    id: 17,
    accountId: 3,
    masjidId: 3,
    transType: "income",
    date: "2021-08-3",
    voucher: "", 
    bank : "", 
    reciever : "", 
    detail : "", 
    voucherNo : "",
    amount: 50000,
  },
  {
    id: 18,
    accountId: 3,
    masjidId: 3,
    transType: "expense",
    date: "2021-08-19",
    voucher: "واؤچر", 
    bank : "سقایہ ویلفئیر سوسائٹی", 
    reciever : "محمد امین خان", 
    detail : "-", 
    voucherNo : "-",
    amount: 40000,
  },
  {
    id: 19,
    accountId: 3,
    masjidId: 0,
    transType: "expense",
    date: "2021-08-8",
    voucher: "واؤچر", 
    bank : "سقایہ ویلفئیر سوسائٹی", 
    reciever : "محمد امین خان", 
    detail : "-", 
    voucherNo : "-",
    amount: 50000,
  },
   ////////////////////////////////////////////////////
  {
    id: 20,
    accountId: 4,
    masjidId: 4,
    transType: "income",
    date: "2021-08-3",
    voucher: "", 
    bank : "", 
    reciever : "", 
    detail : "", 
    voucherNo : "",
    amount: 30000,
  },
  {
    id: 21,
    accountId: 4,
    masjidId: 4,
    transType: "income",
    date: "2021-08-3",
    voucher: "", 
    bank : "", 
    reciever : "", 
    detail : "", 
    voucherNo : "",
    amount: 30000,
  },
  {
    id: 22,
    accountId: 4,
    masjidId: 4,
    transType: "expense",
    date: "2021-08-9",
    voucher: "واؤچر", 
    bank : "سقایہ ویلفئیر سوسائٹی", 
    reciever : "محمد امین خان", 
    detail : "-", 
    voucherNo : "-",
    amount: 20000,
  },
  {
    id: 23,
    accountId: 4,
    masjidId: 1,
    transType: "expense",
    date: "2021-08-9",
    voucher: "واؤچر", 
    bank : "سقایہ ویلفئیر سوسائٹی", 
    reciever : "محمد امین خان", 
    detail : "-", 
    voucherNo : "-",
    amount: 10000,
  },
  {
    id: 24,
    accountId: 4,
    masjidId: 2,
    transType: "expense",
    date: "2021-08-14",
    voucher: "واؤچر", 
    bank : "سقایہ ویلفئیر سوسائٹی", 
    reciever : "محمد امین خان", 
    detail : "-", 
    voucherNo : "-",
    amount: 1000,
  },
];